title: Blog Theme
description: Theme for Jekyll sites
author: Author Name
logo: https://via.placeholder.com/24
theme: null

# Google Analytics
# ga_domain:
# ga_tracking_id: UA-XXXXXXXX-X

header_pages:
  - index.html
  - _pages/posts.html
  - _pages/tags.html
  - _pages/categories.html
  - _pages/404.html

exclude:
  - node_modules
  - vendor
  - blogtheme.gemspec
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.txt
  - package-lock.json
  - package.json
  - README.md

# paginate: 5
# paginate_path: /page:num

plugins:
  - jekyll-sitemap
  # - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "_pages"
      scope: "pages"
    values:
      layout: "page"

# Social
# Update with your usernames
# and uncomment to show/enable
# facebook_url: https://facebook.com/
# github_url:  https://github.com/
# twitter_url: https://twitter.com/
# linkedin_url: https://www.linkedin.com/
# medium_url: https://medium.com/
# instagram_url: https://www.instagram.com/
# dribbble_url: https://dribbble.com/

# TODO: enable once SVGs are updated
# codepen_url: https://codepen.io/
# angellist_url: https://angel.co/

# Customizable Content
recent_posts_title: Recent Posts
recent_posts_content: Nullam risus blandit ac aliquam justo ipsum. Quam mauris volutpat massa dictumst amet.
featured_title: Featured Works
featured_content: Lorem ipsum dolor sit amet consectetur.
services_title: Services
services_content: Nullam risus blandit ac aliquam justo ipsum.
footer_content: "&copy; 2022 Site Name."
